
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 21 14:45:53 ART 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Si = 8;
  public static final int Fin = 4;
  public static final int Numero = 22;
  public static final int Leer = 11;
  public static final int ParentesisAbierto = 14;
  public static final int Entero = 7;
  public static final int ERROR = 23;
  public static final int Identificador = 21;
  public static final int Coma = 17;
  public static final int Inicio = 3;
  public static final int Programa = 2;
  public static final int Variables = 5;
  public static final int Funcion = 6;
  public static final int Sino = 10;
  public static final int ParentesisCerrado = 15;
  public static final int EOF = 0;
  public static final int Escribir = 12;
  public static final int Entonces = 9;
  public static final int error = 1;
  public static final int Modulo = 13;
  public static final int Asignacion = 19;
  public static final int Igual = 18;
  public static final int DosPuntos = 20;
  public static final int PuntoComa = 16;
}

